### ISSUE TITLE
Excluding properties from snapshot

### ISSUE THREAD

**Issue by tpluscode** [tlameiras/chai-snapshot-matcher#10]
I have an object in test which has a generated `id` field.

It would be nice to have a way to exclude it from the comparison. Something like 

```
const sut = {
  foo: 'bar',
  bar: 'baz'
}

expect(sut).to.matchSnapshot(this, {
  except: ['bar']
})
```

This would only compare `foo` property

**Comment by tlameiras** [comment]
Hi @tpluscode,

I really appreciate your suggestions 🙏 
I am adding some unit tests to this project and after that I will start looking at these issues.

**Comment by tlameiras** [comment]
Feature supported since v2.0.1
